### PR TITLE
Workflow enhancements

### PR DESCRIPTION
**Pull request by wdsrocha**
> ⚠️ This PR is small, but it does more than one thing, so I suggest [reviewing per commit](https://github.com/vtex/checkout-ui-tests/pull/119/commits)

#### What is the purpose of this pull request?

1. Improves the run description on Cypress Dashboard by
	* Allowing a custom title instead of the last commit title ([docs, tip #3](https://github.com/cypress-io/github-action#record-test-results-on-cypress-dashboard))
	* Displaying the name of who executed the workflow instead of the last committer name ([docs](https://docs.cypress.io/guides/continuous-integration/introduction#Git-information))
	* Displaying a default avatar instead of the last committer avatar (there is no easy way to get the "correct" avatar)
	* Adding more descriptive tags instead of just `stable` and `beta`
2. Allows filename filtering via grep ([docs](https://github.com/cypress-io/github-action#specs))

**Those enhancements are opinionated, so feel free to disagree about anything.**

#### What problem is this solving?

1. It was hard to identify who or why a workflow execution was triggered because the committer name, avatar and title were all related to the last commit made on `checkout-ui-tests`, which does make sense after a pull request on `checkout-ui-tests` itself, but makes no sense when triggered manually via a workflow dispatch.
2. There was no way to run just a single test or just the tests from a specific account like `vtexgame1nolean`. Filename filtering might not help in 100% of the cases, but it should be useful in the most common scenarios.

#### How should this be manually tested?

1. Go to: <https://github.com/vtex/checkout-ui-tests/actions/workflows/main.yml>
2. Click in the `Run workflow` button
3. Select the `workflow-enhancements` branch
4. Fill the workflow form
	* title: whatever you want :^)
	* environment and workspace can be the default values
	* files to run: use `**/*Peru*` (it will only trigger two tests)
	* parallel containers: 2 (just so it doesn't fire a lot of unnecessary machines)
5. Click in the `Run workflow` button
6. Wait for about a minute
7. [Go to the lastest runs on Cypress Dashboard](https://dashboard.cypress.io/projects/kobqo4/runs) and check your run (if you have no access, just ping me on Slack)

The end result should be something like this:

image

--- 

On a final note, those things are so complicated because Cypress wasn't made to be executed in a separate repository. :gambiarra:

### CODE REVIEW

**Review by carolkrroo — APPROVED** [review]
Awesome! 👏 
I just don't understand why `COMMIT_INFO_EMAIL` is necessary.

**Review by lucasecdb — APPROVED** [review]

**Comment by wdsrocha** [comment]
> I just don't understand why COMMIT_INFO_EMAIL is necessary.

@carolkrroo Because the small avatar image that appears in each run is based on the email. For example, I asked @lbebber to trigger the workflow and this happened:

image

As the default `COMMIT_INFO_EMAIL` value is from the last committer, it used my avatar 🤡

A short solution would be to do something like `COMMIT_INFO_EMAIL=${{ github.email }}`, but there is no way to get the email from the github object 😔. So rather than having an incorrect profile picture, I prefer to have none.

There is probably a way to get the correct email, but I imagine that it would be more complex and take some extra work

**Comment by lucasecdb** [comment]
@wdsrocha I think you can get the commiter email like @thalytafabrine did in this commit: https://github.com/vtex-apps/search/commit/e11cb062ee4cdd9202120e9732a0ab956176c979

**Comment by wdsrocha** [comment]
@lucasecdb the problem is that the committer email _is_ the wrong one. We need to get the email from who triggered the action. I wish that it was available as `${{ github.event.workflow_run.sender.email }}` or something like that, but it isn't (as seen [here](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads))

**Comment by wdsrocha** [comment]
I'll merge for now, but if you both have any idea on how to retrieve this email, let us know!

**Pull request merged**
